# -*- coding: utf-8 -*-
"""Project_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OKYbCjNG68JTwryWO0rtxl4VMCoZRiWJ
"""

import pandas as pd
import numpy as np

df = pd.read_csv('/content/finance_data.txt')
df

# How many total records are present in the file?
df['HDFC Bank'].count()

# List all companies that have a rating of 'A+'.
df[df['C']== 'A+']['HDFC Bank']

# Count how many companies are located in 'Mumbai'.
comp_mumbai = df[df['Bangalore'] == 'Mumbai']
comp_mumbai['Bangalore'].count()

# Print the names of companies with revenue greater than 800 crores.
df[df['300'] > 800]['HDFC Bank']

# Calculate the total revenue generated by all companies combined.
df['300'].sum()

# List all unique sectors mentioned in the file.
df['Retail Banking'].unique()

# Print the names of companies that are either located in 'Delhi' or have a rating of 'B'.
df[(df['Bangalore']=='Delhi') | (df['C'] == 'B')]

How many companies belong to the 'Loans' sector?
df_loan = df[df['Retail Banking']=='Loans']
df_loan['Retail Banking'].count()

# Print the names of companies whose revenue is between 400 and 600 crores.
df[(df['300']>400) & (df['300']<800)]['HDFC Bank']

# Create a list of all companies with ratings other than 'A+'.
df[df['C']!= 'A+']['HDFC Bank']